### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by timhooker** [mikehardy/buildcache-action#100]
I'm getting this error while running the buildcache-action:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
```

Is it possible to update your action.yml to reflect a newer version of node?

**Comment by mikehardy** [comment]
not sure if it's breaking or not, so I issued it as v2

**Comment by timhooker** [comment]
Thank you! This action and your writeup on it has been really helpful.
