### ISSUE TITLE
Fix github react-native compile workflow to upload from non-relative path

### ISSUE THREAD

**Issue by mikehardy** [mikehardy/buildcache-action#35]
These are actually more serious - I'm not sure exactly how to fail the react-native compile test based on this type of failure (I did not spend much time investigating though, TBH - I just visually inspect), but there's a problem here

https://github.com/mikehardy/buildcache-action/pull/34/checks?check_run_id=3125987994#step:27:20

```

Warning: buildcache: unable to upload buildlog: Error: File ../custom_buildcache.log does not exist
Warning: buildcache: unable to delete buildcache.log Error: ENOENT: no such file or directory, unlink '../custom_buildcache.log'
buildcache: saving cache with key "buildcache-react-native-compile-2021-07-21T16:28:25.384Z".
Warning: buildcache: caching not working: AssertionError [ERR_ASSERTION]: Invalid pattern '../custom_buildcache_dir'. Relative pathing '.' and '..' is not allowed.

```

_Originally posted by @mikehardy in https://github.com/mikehardy/buildcache-action/issues/34#issuecomment-884326134_

**Comment by mikehardy** [comment]
Suggestion by @orgads https://github.com/mikehardy/buildcache-action/pull/34#issuecomment-884328354

> I suppose the intent was to use a directory relative to github workspace. This can be done by detecting that the path is relative, and the using path.resolve with the workspace as base.

**Comment by mikehardy** [comment]
No obligation at all (it's open source! just do it if you enjoy it and it's useful right?) but I invited you as a collaborator to the repo. Even if you accept, still no obligation. But if you like, happy to allow authority over the codebase, your work is really clean

**Comment by orgads** [comment]
I appreciate that :)
