### ISSUE TITLE
Integration to any CI/CD or even in Local

### ISSUE THREAD

**Issue by Alaa-Ben** [mikehardy/buildcache-action#55]
Hi ! 
First of all, thanks for your work, amazing ! 
I was wondering if it was possible to get some help to make this more "available" for everyone, people who don't run Github Actions in particular. Any ideas on how to achieve that ? I found [this link here](https://zanechua.com/blog/reduce-react-native-xcode-build-time) that explains how to setup buildcache, but not how to cache builds, etc. Would be awesome if you could shed some light here !
Thanks in advance.

**Comment by mikehardy** [comment]
Hi there! Sorry, it is *literally* a github action. That's the whole purpose of it.
If you want availability in other domains, use buildcache directly, and consult the buildcache documentation for how to use + integrate

**Comment by Alaa-Ben** [comment]
I know, just wanted some help concerning the checksum part because in the buildcache repo, there is no talk about whether or not a check for changes is done. And if not, how to implement it.

**Comment by mikehardy** [comment]
That's literally the entire point of a build cache (either buildcache or ccache) etc. That should be all transparent to cache users. I replied on your related comment on the buildcache repo

**Comment by Alaa-Ben** [comment]
Perfect, thanks again !
