### ISSUE TITLE
buildcache very small with Flutter

### ISSUE THREAD

**Issue by stevenspiel** [mikehardy/buildcache-action#94]
You mention FlutterFire in the Readme, so I'm assuming you have some advice. The size of the buildcache is quite small on my Flutter project. Do you have any recommendations for different config I could try?

```
Post job cleanup.
/Users/runner/work/my-app/my-app/buildcache/bin/buildcache -s
Cache status:
Entries in cache:  3
Cache size:        534.1 KiB (0.1%)
Direct hits:       0
Direct misses:     0
Local hits:        0
Local misses:      3
Remote hits:       0
Remote misses:     0
Misses:            3
Direct hit ratio:  0.0%
Local hit ratio:   0.0%
Remote hit ratio:  0.0%
Hit ratio:         0.0%
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "buildcache_log" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 150 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!

The raw size of all the files that were specified for upload is 213 bytes
The size of all the files that were uploaded is 150 bytes. This takes into account any gzip compression used to reduce the upload size, time and storage

Note: The size of downloaded zips can differ significantly from the reported size. For more information see: https://github.com/actions/upload-artifact#zipped-artifact-downloads 

buildcache: uploaded buildcache.log file (consumed 150 bytes of artifact storage)
buildcache: saving cache with key "buildcache-2022-08-27T16:22:36.994Z".
/usr/local/bin/gtar --posix --use-compress-program zstd -T0 -cf cache.tzst --exclude cache.tzst -P -C /Users/runner/work/my-app/my-app --files-from manifest.txt --delay-directory-restore
Cache Size: ~0 MB (407961 B)
Cache saved successfully
```

**Comment by mikehardy** [comment]
For that use (Xcode, building an iOS project - that's my guess for FlutterFire use, yes?) I would recommend ccache-action, not this action

You'll need some special settings of fuzziness and you'll want to modify your Podfile to use relative paths for the compiler tools, and react-native actually does a good job of documenting it - it will apply to Flutter projects as well:

https://reactnative.dev/docs/build-speed#xcode-specific-setup

the Podfile snippet is all you need to use relative paths, you set the needed variables like this

https://github.com/invertase/react-native-firebase/blob/feac7f8c8b85c3cf87a34dc9a75ddb7b7b9c034b/.github/workflows/tests_e2e_ios.yml#L139-L144

With a warm cache in CI we build our e2e test app for react-native-firebase in approximately a couple minutes, from source https://github.com/invertase/react-native-firebase/runs/8051025185?check_suite_focus=true#step:19:1

Hope this helps!

**Comment by stevenspiel** [comment]
Great! This has been very helpful and shaved ~10 minutes off of our build. Thank you!
