### ISSUE TITLE
Add option to silent failures

### ISSUE THREAD

**Issue by ncooke3** [mikehardy/buildcache-action#96]
Sometimes this action will fail in the setup or cleanup step in a GHA job. See an [example log](https://github.com/firebase/firebase-ios-sdk/actions/runs/3120981096/jobs/5061991974). 

I'm not 100% sure why it fails, but Firebase uses this action extensively so it may be related to PRs that trigger a lot of CI jobs. 

What do you think about a config option to silent such failures? The idea would be that the action runs on a best effort basis and never causes the action to fail when something like a transient network error occurs in either the cache setup or teardown steps?

**Comment by mikehardy** [comment]
Interesting re: the firebase comment, I started this action specifically to build FirebaseFirestore more quickly, but then quickly switched (back...sort of) to ccache (and ccache-action) once ccache was able to handle iOS builds better. And I still keep this action on life support for existing users, but in my experience ccache is the most heavily maintained caching system and now it works great so I use it everywhere (here's an example showing the exact config we use: https://github.com/invertase/react-native-firebase/blob/ccb09a9e775c71b91bdf34bf1192f105b2c2d998/.github/workflows/tests_e2e_ios.yml#L143-L146)

I even wrote it up for react-native main website ;-) 

https://reactnative.dev/docs/0.69/build-speed#local-caches

So, anyway - ccache is likely better but here we are with buildcache :-)

And for that I can say I will happily merge any reasonable PR that handles your use case - post it up. I will say I have great luck with https://github.com/marketplace/actions/retry-step

I wonder if that could somehow be made into an API and used here, or if the same general idea could be employed. It's critical for me in the repos I run to boost signal-to-noise by getting rid of most false negatives from transient network problems

Cheers

**Comment by ncooke3** [comment]
Thanks for the info Mike! I have not heard of ccache-action and will look into that. I'll do a little more experimenting with this action and the ccache-action. I'll close this issue for now and re-open if I have a PR/something to share. Thanks :)

**Comment by mikehardy** [comment]
Sure thing, happy to help, faster build times for the world ;-)
